swagger: "2.0"
info:
  title: User flex feature raft server
  version: "1.0"
tags:
  - name: RaftService
consumes:
  - application/json
produces:
  - application/json
paths:
  /user-flex-feature/api/v1/raft/join:
    post:
      operationId: RaftService_Join
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1EmptyResponse'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1JoinRequest'
      tags:
        - RaftService
  /user-flex-feature/api/v1/raft/leave:
    post:
      operationId: RaftService_Leave
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1EmptyResponse'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1LeaveRequest'
      tags:
        - RaftService
definitions:
  v1EmptyResponse:
    type: object
  v1JoinRequest:
    type: object
    properties:
      id:
        type: string
      addr:
        type: string
    required:
      - id
      - addr
  v1LeaveRequest:
    type: object
    properties:
      id:
        type: string
    required:
      - id
