// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: docs/schema/ofrep/v1/schema.proto

package ofrep

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeneralErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorDetails string `protobuf:"bytes,1,opt,name=error_details,json=errorDetails,proto3" json:"error_details,omitempty"`
}

func (x *GeneralErrorResponse) Reset() {
	*x = GeneralErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneralErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralErrorResponse) ProtoMessage() {}

func (x *GeneralErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralErrorResponse.ProtoReflect.Descriptor instead.
func (*GeneralErrorResponse) Descriptor() ([]byte, []int) {
	return file_docs_schema_ofrep_v1_schema_proto_rawDescGZIP(), []int{0}
}

func (x *GeneralErrorResponse) GetErrorDetails() string {
	if x != nil {
		return x.ErrorDetails
	}
	return ""
}

type GetConfigurationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IfNoneMatch string `protobuf:"bytes,1,opt,name=if_none_match,json=ifNoneMatch,proto3" json:"if_none_match,omitempty"`
}

func (x *GetConfigurationRequest) Reset() {
	*x = GetConfigurationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigurationRequest) ProtoMessage() {}

func (x *GetConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigurationRequest.ProtoReflect.Descriptor instead.
func (*GetConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_docs_schema_ofrep_v1_schema_proto_rawDescGZIP(), []int{1}
}

func (x *GetConfigurationRequest) GetIfNoneMatch() string {
	if x != nil {
		return x.IfNoneMatch
	}
	return ""
}

type GetConfigurationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Configuration *Configuration `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	ETag          string         `protobuf:"bytes,2,opt,name=e_tag,json=eTag,proto3" json:"e_tag,omitempty"`
}

func (x *GetConfigurationResponse) Reset() {
	*x = GetConfigurationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigurationResponse) ProtoMessage() {}

func (x *GetConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigurationResponse.ProtoReflect.Descriptor instead.
func (*GetConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_docs_schema_ofrep_v1_schema_proto_rawDescGZIP(), []int{2}
}

func (x *GetConfigurationResponse) GetConfiguration() *Configuration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *GetConfigurationResponse) GetETag() string {
	if x != nil {
		return x.ETag
	}
	return ""
}

type EvaluateFlagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string             `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Context *EvaluationContext `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
}

func (x *EvaluateFlagRequest) Reset() {
	*x = EvaluateFlagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluateFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateFlagRequest) ProtoMessage() {}

func (x *EvaluateFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateFlagRequest.ProtoReflect.Descriptor instead.
func (*EvaluateFlagRequest) Descriptor() ([]byte, []int) {
	return file_docs_schema_ofrep_v1_schema_proto_rawDescGZIP(), []int{3}
}

func (x *EvaluateFlagRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EvaluateFlagRequest) GetContext() *EvaluationContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type EvaluateFlagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*EvaluateFlagResponse_Success
	//	*EvaluateFlagResponse_Failure
	Result isEvaluateFlagResponse_Result `protobuf_oneof:"result"`
}

func (x *EvaluateFlagResponse) Reset() {
	*x = EvaluateFlagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluateFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateFlagResponse) ProtoMessage() {}

func (x *EvaluateFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateFlagResponse.ProtoReflect.Descriptor instead.
func (*EvaluateFlagResponse) Descriptor() ([]byte, []int) {
	return file_docs_schema_ofrep_v1_schema_proto_rawDescGZIP(), []int{4}
}

func (m *EvaluateFlagResponse) GetResult() isEvaluateFlagResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *EvaluateFlagResponse) GetSuccess() *EvaluationSuccess {
	if x, ok := x.GetResult().(*EvaluateFlagResponse_Success); ok {
		return x.Success
	}
	return nil
}

func (x *EvaluateFlagResponse) GetFailure() *EvaluationFailure {
	if x, ok := x.GetResult().(*EvaluateFlagResponse_Failure); ok {
		return x.Failure
	}
	return nil
}

type isEvaluateFlagResponse_Result interface {
	isEvaluateFlagResponse_Result()
}

type EvaluateFlagResponse_Success struct {
	Success *EvaluationSuccess `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type EvaluateFlagResponse_Failure struct {
	Failure *EvaluationFailure `protobuf:"bytes,2,opt,name=failure,proto3,oneof"`
}

func (*EvaluateFlagResponse_Success) isEvaluateFlagResponse_Result() {}

func (*EvaluateFlagResponse_Failure) isEvaluateFlagResponse_Result() {}

type EvaluateFlagsBulkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Context *EvaluationContext `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
}

func (x *EvaluateFlagsBulkRequest) Reset() {
	*x = EvaluateFlagsBulkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluateFlagsBulkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateFlagsBulkRequest) ProtoMessage() {}

func (x *EvaluateFlagsBulkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateFlagsBulkRequest.ProtoReflect.Descriptor instead.
func (*EvaluateFlagsBulkRequest) Descriptor() ([]byte, []int) {
	return file_docs_schema_ofrep_v1_schema_proto_rawDescGZIP(), []int{5}
}

func (x *EvaluateFlagsBulkRequest) GetContext() *EvaluationContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type EvaluateFlagsBulkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flags []*EvaluationResult `protobuf:"bytes,1,rep,name=flags,proto3" json:"flags,omitempty"`
	ETag  string              `protobuf:"bytes,2,opt,name=e_tag,json=eTag,proto3" json:"e_tag,omitempty"`
}

func (x *EvaluateFlagsBulkResponse) Reset() {
	*x = EvaluateFlagsBulkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluateFlagsBulkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateFlagsBulkResponse) ProtoMessage() {}

func (x *EvaluateFlagsBulkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateFlagsBulkResponse.ProtoReflect.Descriptor instead.
func (*EvaluateFlagsBulkResponse) Descriptor() ([]byte, []int) {
	return file_docs_schema_ofrep_v1_schema_proto_rawDescGZIP(), []int{6}
}

func (x *EvaluateFlagsBulkResponse) GetFlags() []*EvaluationResult {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *EvaluateFlagsBulkResponse) GetETag() string {
	if x != nil {
		return x.ETag
	}
	return ""
}

type Configuration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Capabilities *Capability `protobuf:"bytes,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_docs_schema_ofrep_v1_schema_proto_rawDescGZIP(), []int{7}
}

func (x *Configuration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Configuration) GetCapabilities() *Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type Capability struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CacheInvalidation *FeatureCacheInvalidation `protobuf:"bytes,1,opt,name=cache_invalidation,json=cacheInvalidation,proto3" json:"cache_invalidation,omitempty"`
}

func (x *Capability) Reset() {
	*x = Capability{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_docs_schema_ofrep_v1_schema_proto_rawDescGZIP(), []int{8}
}

func (x *Capability) GetCacheInvalidation() *FeatureCacheInvalidation {
	if x != nil {
		return x.CacheInvalidation
	}
	return nil
}

type FeatureCacheInvalidation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Polling *Polling `protobuf:"bytes,1,opt,name=polling,proto3" json:"polling,omitempty"`
}

func (x *FeatureCacheInvalidation) Reset() {
	*x = FeatureCacheInvalidation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeatureCacheInvalidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureCacheInvalidation) ProtoMessage() {}

func (x *FeatureCacheInvalidation) ProtoReflect() protoreflect.Message {
	mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureCacheInvalidation.ProtoReflect.Descriptor instead.
func (*FeatureCacheInvalidation) Descriptor() ([]byte, []int) {
	return file_docs_schema_ofrep_v1_schema_proto_rawDescGZIP(), []int{9}
}

func (x *FeatureCacheInvalidation) GetPolling() *Polling {
	if x != nil {
		return x.Polling
	}
	return nil
}

type Polling struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled            bool    `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	MinPollingInterval float64 `protobuf:"fixed64,2,opt,name=min_polling_interval,json=minPollingInterval,proto3" json:"min_polling_interval,omitempty"`
}

func (x *Polling) Reset() {
	*x = Polling{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Polling) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Polling) ProtoMessage() {}

func (x *Polling) ProtoReflect() protoreflect.Message {
	mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Polling.ProtoReflect.Descriptor instead.
func (*Polling) Descriptor() ([]byte, []int) {
	return file_docs_schema_ofrep_v1_schema_proto_rawDescGZIP(), []int{10}
}

func (x *Polling) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Polling) GetMinPollingInterval() float64 {
	if x != nil {
		return x.MinPollingInterval
	}
	return 0
}

type EvaluationContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Properties *structpb.Struct `protobuf:"bytes,1,opt,name=properties,proto3" json:"properties,omitempty"`
}

func (x *EvaluationContext) Reset() {
	*x = EvaluationContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluationContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationContext) ProtoMessage() {}

func (x *EvaluationContext) ProtoReflect() protoreflect.Message {
	mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationContext.ProtoReflect.Descriptor instead.
func (*EvaluationContext) Descriptor() ([]byte, []int) {
	return file_docs_schema_ofrep_v1_schema_proto_rawDescGZIP(), []int{11}
}

func (x *EvaluationContext) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

type EvaluationSuccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      string               `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Reason   string               `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Variant  string               `protobuf:"bytes,3,opt,name=variant,proto3" json:"variant,omitempty"`
	Metadata map[string]*Metadata `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Types that are assignable to Value:
	//
	//	*EvaluationSuccess_BoolValue
	//	*EvaluationSuccess_StringValue
	//	*EvaluationSuccess_IntegerValue
	//	*EvaluationSuccess_DoubleValue
	//	*EvaluationSuccess_ObjectValue
	Value isEvaluationSuccess_Value `protobuf_oneof:"value"`
}

func (x *EvaluationSuccess) Reset() {
	*x = EvaluationSuccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluationSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationSuccess) ProtoMessage() {}

func (x *EvaluationSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationSuccess.ProtoReflect.Descriptor instead.
func (*EvaluationSuccess) Descriptor() ([]byte, []int) {
	return file_docs_schema_ofrep_v1_schema_proto_rawDescGZIP(), []int{12}
}

func (x *EvaluationSuccess) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EvaluationSuccess) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *EvaluationSuccess) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

func (x *EvaluationSuccess) GetMetadata() map[string]*Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (m *EvaluationSuccess) GetValue() isEvaluationSuccess_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *EvaluationSuccess) GetBoolValue() bool {
	if x, ok := x.GetValue().(*EvaluationSuccess_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (x *EvaluationSuccess) GetStringValue() string {
	if x, ok := x.GetValue().(*EvaluationSuccess_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (x *EvaluationSuccess) GetIntegerValue() int64 {
	if x, ok := x.GetValue().(*EvaluationSuccess_IntegerValue); ok {
		return x.IntegerValue
	}
	return 0
}

func (x *EvaluationSuccess) GetDoubleValue() float64 {
	if x, ok := x.GetValue().(*EvaluationSuccess_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (x *EvaluationSuccess) GetObjectValue() *structpb.Struct {
	if x, ok := x.GetValue().(*EvaluationSuccess_ObjectValue); ok {
		return x.ObjectValue
	}
	return nil
}

type isEvaluationSuccess_Value interface {
	isEvaluationSuccess_Value()
}

type EvaluationSuccess_BoolValue struct {
	BoolValue bool `protobuf:"varint,5,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type EvaluationSuccess_StringValue struct {
	StringValue string `protobuf:"bytes,6,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type EvaluationSuccess_IntegerValue struct {
	IntegerValue int64 `protobuf:"varint,7,opt,name=integer_value,json=integerValue,proto3,oneof"`
}

type EvaluationSuccess_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,8,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type EvaluationSuccess_ObjectValue struct {
	ObjectValue *structpb.Struct `protobuf:"bytes,9,opt,name=object_value,json=objectValue,proto3,oneof"`
}

func (*EvaluationSuccess_BoolValue) isEvaluationSuccess_Value() {}

func (*EvaluationSuccess_StringValue) isEvaluationSuccess_Value() {}

func (*EvaluationSuccess_IntegerValue) isEvaluationSuccess_Value() {}

func (*EvaluationSuccess_DoubleValue) isEvaluationSuccess_Value() {}

func (*EvaluationSuccess_ObjectValue) isEvaluationSuccess_Value() {}

type EvaluationFailure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key          string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ErrorCode    string `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorDetails string `protobuf:"bytes,3,opt,name=error_details,json=errorDetails,proto3" json:"error_details,omitempty"`
}

func (x *EvaluationFailure) Reset() {
	*x = EvaluationFailure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluationFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationFailure) ProtoMessage() {}

func (x *EvaluationFailure) ProtoReflect() protoreflect.Message {
	mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationFailure.ProtoReflect.Descriptor instead.
func (*EvaluationFailure) Descriptor() ([]byte, []int) {
	return file_docs_schema_ofrep_v1_schema_proto_rawDescGZIP(), []int{13}
}

func (x *EvaluationFailure) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EvaluationFailure) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *EvaluationFailure) GetErrorDetails() string {
	if x != nil {
		return x.ErrorDetails
	}
	return ""
}

type Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*Metadata_BooleanValue
	//	*Metadata_StringValue
	//	*Metadata_NumberValue
	Type isMetadata_Type `protobuf_oneof:"type"`
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_docs_schema_ofrep_v1_schema_proto_rawDescGZIP(), []int{14}
}

func (m *Metadata) GetType() isMetadata_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Metadata) GetBooleanValue() bool {
	if x, ok := x.GetType().(*Metadata_BooleanValue); ok {
		return x.BooleanValue
	}
	return false
}

func (x *Metadata) GetStringValue() string {
	if x, ok := x.GetType().(*Metadata_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (x *Metadata) GetNumberValue() float64 {
	if x, ok := x.GetType().(*Metadata_NumberValue); ok {
		return x.NumberValue
	}
	return 0
}

type isMetadata_Type interface {
	isMetadata_Type()
}

type Metadata_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,1,opt,name=boolean_value,json=booleanValue,proto3,oneof"`
}

type Metadata_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Metadata_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,3,opt,name=number_value,json=numberValue,proto3,oneof"`
}

func (*Metadata_BooleanValue) isMetadata_Type() {}

func (*Metadata_StringValue) isMetadata_Type() {}

func (*Metadata_NumberValue) isMetadata_Type() {}

type EvaluationResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*EvaluationResult_Success
	//	*EvaluationResult_Failure
	Result isEvaluationResult_Result `protobuf_oneof:"result"`
}

func (x *EvaluationResult) Reset() {
	*x = EvaluationResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationResult) ProtoMessage() {}

func (x *EvaluationResult) ProtoReflect() protoreflect.Message {
	mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationResult.ProtoReflect.Descriptor instead.
func (*EvaluationResult) Descriptor() ([]byte, []int) {
	return file_docs_schema_ofrep_v1_schema_proto_rawDescGZIP(), []int{15}
}

func (m *EvaluationResult) GetResult() isEvaluationResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *EvaluationResult) GetSuccess() *EvaluationSuccess {
	if x, ok := x.GetResult().(*EvaluationResult_Success); ok {
		return x.Success
	}
	return nil
}

func (x *EvaluationResult) GetFailure() *EvaluationFailure {
	if x, ok := x.GetResult().(*EvaluationResult_Failure); ok {
		return x.Failure
	}
	return nil
}

type isEvaluationResult_Result interface {
	isEvaluationResult_Result()
}

type EvaluationResult_Success struct {
	Success *EvaluationSuccess `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type EvaluationResult_Failure struct {
	Failure *EvaluationFailure `protobuf:"bytes,2,opt,name=failure,proto3,oneof"`
}

func (*EvaluationResult_Success) isEvaluationResult_Result() {}

func (*EvaluationResult_Failure) isEvaluationResult_Result() {}

type FlagNotFound struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key          string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ErrorCode    string `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorDetails string `protobuf:"bytes,3,opt,name=error_details,json=errorDetails,proto3" json:"error_details,omitempty"`
}

func (x *FlagNotFound) Reset() {
	*x = FlagNotFound{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlagNotFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagNotFound) ProtoMessage() {}

func (x *FlagNotFound) ProtoReflect() protoreflect.Message {
	mi := &file_docs_schema_ofrep_v1_schema_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagNotFound.ProtoReflect.Descriptor instead.
func (*FlagNotFound) Descriptor() ([]byte, []int) {
	return file_docs_schema_ofrep_v1_schema_proto_rawDescGZIP(), []int{16}
}

func (x *FlagNotFound) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FlagNotFound) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *FlagNotFound) GetErrorDetails() string {
	if x != nil {
		return x.ErrorDetails
	}
	return ""
}

var File_docs_schema_ofrep_v1_schema_proto protoreflect.FileDescriptor

var file_docs_schema_ofrep_v1_schema_proto_rawDesc = []byte{
	0x0a, 0x21, 0x64, 0x6f, 0x63, 0x73, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x6f, 0x66,
	0x72, 0x65, 0x70, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6f, 0x66, 0x72, 0x65, 0x70, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a, 0x14, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x64, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x3d, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x69, 0x66, 0x5f, 0x6e, 0x6f, 0x6e, 0x65, 0x5f, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x66, 0x4e, 0x6f,
	0x6e, 0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x22, 0x6e, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6f, 0x66, 0x72,
	0x65, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x13, 0x0a, 0x05, 0x65, 0x5f, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x65, 0x54, 0x61, 0x67, 0x22, 0x5e, 0x0a, 0x13, 0x45, 0x76, 0x61, 0x6c, 0x75,
	0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x35, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x66, 0x72, 0x65, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x61,
	0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0x92, 0x01, 0x0a, 0x14, 0x45, 0x76, 0x61, 0x6c,
	0x75, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x37, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x66, 0x72, 0x65, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x61,
	0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x48, 0x00,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x37, 0x0a, 0x07, 0x66, 0x61, 0x69,
	0x6c, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x66, 0x72,
	0x65, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x48, 0x00, 0x52, 0x07, 0x66, 0x61, 0x69, 0x6c, 0x75,
	0x72, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x51, 0x0a, 0x18,
	0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x42, 0x75, 0x6c,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x66, 0x72, 0x65,
	0x70, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22,
	0x62, 0x0a, 0x19, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x73,
	0x42, 0x75, 0x6c, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x05,
	0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6f, 0x66,
	0x72, 0x65, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x12, 0x13,
	0x0a, 0x05, 0x65, 0x5f, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x65,
	0x54, 0x61, 0x67, 0x22, 0x5d, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x0c, 0x63, 0x61, 0x70, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x6f, 0x66, 0x72, 0x65, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x52, 0x0c, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x22, 0x5f, 0x0a, 0x0a, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x12, 0x51, 0x0a, 0x12, 0x63, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6f,
	0x66, 0x72, 0x65, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x11, 0x63, 0x61, 0x63, 0x68, 0x65, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x47, 0x0a, 0x18, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x2b, 0x0a, 0x07, 0x70, 0x6f, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x6f, 0x66, 0x72, 0x65, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x6c, 0x6c,
	0x69, 0x6e, 0x67, 0x52, 0x07, 0x70, 0x6f, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x22, 0x55, 0x0a, 0x07,
	0x50, 0x6f, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x12, 0x30, 0x0a, 0x14, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x6f, 0x6c, 0x6c, 0x69, 0x6e, 0x67,
	0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x12, 0x6d, 0x69, 0x6e, 0x50, 0x6f, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x61, 0x6c, 0x22, 0x4c, 0x0a, 0x11, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x37, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65,
	0x73, 0x22, 0xc8, 0x03, 0x0a, 0x11, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x12, 0x45, 0x0a, 0x08, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e,
	0x6f, 0x66, 0x72, 0x65, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x1f, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x25, 0x0a, 0x0d, 0x69, 0x6e, 0x74, 0x65,
	0x67, 0x65, 0x72, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x48,
	0x00, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x23, 0x0a, 0x0c, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x3c, 0x0a, 0x0c, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x1a, 0x4f, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x66, 0x72, 0x65, 0x70, 0x2e, 0x76, 0x31, 0x2e,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x69, 0x0a, 0x11,
	0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x83, 0x01, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x0d, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x0c, 0x62,
	0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x23, 0x0a, 0x0c, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x0b, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x8e, 0x01,
	0x0a, 0x10, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x37, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x66, 0x72, 0x65, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x45,
	0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x48, 0x00, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x37, 0x0a, 0x07, 0x66,
	0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f,
	0x66, 0x72, 0x65, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x48, 0x00, 0x52, 0x07, 0x66, 0x61, 0x69,
	0x6c, 0x75, 0x72, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x64,
	0x0a, 0x0c, 0x46, 0x6c, 0x61, 0x67, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x32, 0x96, 0x02, 0x0a, 0x0c, 0x4f, 0x46, 0x52, 0x45, 0x50, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x59, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x2e, 0x6f, 0x66, 0x72, 0x65,
	0x70, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6f,
	0x66, 0x72, 0x65, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4d, 0x0a, 0x0c, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67,
	0x12, 0x1d, 0x2e, 0x6f, 0x66, 0x72, 0x65, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x61, 0x6c,
	0x75, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x6f, 0x66, 0x72, 0x65, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75,
	0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x5c, 0x0a, 0x11, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x73,
	0x42, 0x75, 0x6c, 0x6b, 0x12, 0x22, 0x2e, 0x6f, 0x66, 0x72, 0x65, 0x70, 0x2e, 0x76, 0x31, 0x2e,
	0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x42, 0x75, 0x6c,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x6f, 0x66, 0x72, 0x65, 0x70,
	0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67,
	0x73, 0x42, 0x75, 0x6c, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a,
	0x07, 0x2e, 0x2f, 0x6f, 0x66, 0x72, 0x65, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_docs_schema_ofrep_v1_schema_proto_rawDescOnce sync.Once
	file_docs_schema_ofrep_v1_schema_proto_rawDescData = file_docs_schema_ofrep_v1_schema_proto_rawDesc
)

func file_docs_schema_ofrep_v1_schema_proto_rawDescGZIP() []byte {
	file_docs_schema_ofrep_v1_schema_proto_rawDescOnce.Do(func() {
		file_docs_schema_ofrep_v1_schema_proto_rawDescData = protoimpl.X.CompressGZIP(file_docs_schema_ofrep_v1_schema_proto_rawDescData)
	})
	return file_docs_schema_ofrep_v1_schema_proto_rawDescData
}

var file_docs_schema_ofrep_v1_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_docs_schema_ofrep_v1_schema_proto_goTypes = []interface{}{
	(*GeneralErrorResponse)(nil),      // 0: ofrep.v1.GeneralErrorResponse
	(*GetConfigurationRequest)(nil),   // 1: ofrep.v1.GetConfigurationRequest
	(*GetConfigurationResponse)(nil),  // 2: ofrep.v1.GetConfigurationResponse
	(*EvaluateFlagRequest)(nil),       // 3: ofrep.v1.EvaluateFlagRequest
	(*EvaluateFlagResponse)(nil),      // 4: ofrep.v1.EvaluateFlagResponse
	(*EvaluateFlagsBulkRequest)(nil),  // 5: ofrep.v1.EvaluateFlagsBulkRequest
	(*EvaluateFlagsBulkResponse)(nil), // 6: ofrep.v1.EvaluateFlagsBulkResponse
	(*Configuration)(nil),             // 7: ofrep.v1.Configuration
	(*Capability)(nil),                // 8: ofrep.v1.Capability
	(*FeatureCacheInvalidation)(nil),  // 9: ofrep.v1.FeatureCacheInvalidation
	(*Polling)(nil),                   // 10: ofrep.v1.Polling
	(*EvaluationContext)(nil),         // 11: ofrep.v1.EvaluationContext
	(*EvaluationSuccess)(nil),         // 12: ofrep.v1.EvaluationSuccess
	(*EvaluationFailure)(nil),         // 13: ofrep.v1.EvaluationFailure
	(*Metadata)(nil),                  // 14: ofrep.v1.Metadata
	(*EvaluationResult)(nil),          // 15: ofrep.v1.EvaluationResult
	(*FlagNotFound)(nil),              // 16: ofrep.v1.FlagNotFound
	nil,                               // 17: ofrep.v1.EvaluationSuccess.MetadataEntry
	(*structpb.Struct)(nil),           // 18: google.protobuf.Struct
}
var file_docs_schema_ofrep_v1_schema_proto_depIdxs = []int32{
	7,  // 0: ofrep.v1.GetConfigurationResponse.configuration:type_name -> ofrep.v1.Configuration
	11, // 1: ofrep.v1.EvaluateFlagRequest.context:type_name -> ofrep.v1.EvaluationContext
	12, // 2: ofrep.v1.EvaluateFlagResponse.success:type_name -> ofrep.v1.EvaluationSuccess
	13, // 3: ofrep.v1.EvaluateFlagResponse.failure:type_name -> ofrep.v1.EvaluationFailure
	11, // 4: ofrep.v1.EvaluateFlagsBulkRequest.context:type_name -> ofrep.v1.EvaluationContext
	15, // 5: ofrep.v1.EvaluateFlagsBulkResponse.flags:type_name -> ofrep.v1.EvaluationResult
	8,  // 6: ofrep.v1.Configuration.capabilities:type_name -> ofrep.v1.Capability
	9,  // 7: ofrep.v1.Capability.cache_invalidation:type_name -> ofrep.v1.FeatureCacheInvalidation
	10, // 8: ofrep.v1.FeatureCacheInvalidation.polling:type_name -> ofrep.v1.Polling
	18, // 9: ofrep.v1.EvaluationContext.properties:type_name -> google.protobuf.Struct
	17, // 10: ofrep.v1.EvaluationSuccess.metadata:type_name -> ofrep.v1.EvaluationSuccess.MetadataEntry
	18, // 11: ofrep.v1.EvaluationSuccess.object_value:type_name -> google.protobuf.Struct
	12, // 12: ofrep.v1.EvaluationResult.success:type_name -> ofrep.v1.EvaluationSuccess
	13, // 13: ofrep.v1.EvaluationResult.failure:type_name -> ofrep.v1.EvaluationFailure
	14, // 14: ofrep.v1.EvaluationSuccess.MetadataEntry.value:type_name -> ofrep.v1.Metadata
	1,  // 15: ofrep.v1.OFREPService.GetConfiguration:input_type -> ofrep.v1.GetConfigurationRequest
	3,  // 16: ofrep.v1.OFREPService.EvaluateFlag:input_type -> ofrep.v1.EvaluateFlagRequest
	5,  // 17: ofrep.v1.OFREPService.EvaluateFlagsBulk:input_type -> ofrep.v1.EvaluateFlagsBulkRequest
	2,  // 18: ofrep.v1.OFREPService.GetConfiguration:output_type -> ofrep.v1.GetConfigurationResponse
	4,  // 19: ofrep.v1.OFREPService.EvaluateFlag:output_type -> ofrep.v1.EvaluateFlagResponse
	6,  // 20: ofrep.v1.OFREPService.EvaluateFlagsBulk:output_type -> ofrep.v1.EvaluateFlagsBulkResponse
	18, // [18:21] is the sub-list for method output_type
	15, // [15:18] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_docs_schema_ofrep_v1_schema_proto_init() }
func file_docs_schema_ofrep_v1_schema_proto_init() {
	if File_docs_schema_ofrep_v1_schema_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_docs_schema_ofrep_v1_schema_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneralErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_schema_ofrep_v1_schema_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConfigurationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_schema_ofrep_v1_schema_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConfigurationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_schema_ofrep_v1_schema_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvaluateFlagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_schema_ofrep_v1_schema_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvaluateFlagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_schema_ofrep_v1_schema_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvaluateFlagsBulkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_schema_ofrep_v1_schema_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvaluateFlagsBulkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_schema_ofrep_v1_schema_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Configuration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_schema_ofrep_v1_schema_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Capability); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_schema_ofrep_v1_schema_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeatureCacheInvalidation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_schema_ofrep_v1_schema_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Polling); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_schema_ofrep_v1_schema_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvaluationContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_schema_ofrep_v1_schema_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvaluationSuccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_schema_ofrep_v1_schema_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvaluationFailure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_schema_ofrep_v1_schema_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_schema_ofrep_v1_schema_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvaluationResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_schema_ofrep_v1_schema_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlagNotFound); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_docs_schema_ofrep_v1_schema_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*EvaluateFlagResponse_Success)(nil),
		(*EvaluateFlagResponse_Failure)(nil),
	}
	file_docs_schema_ofrep_v1_schema_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*EvaluationSuccess_BoolValue)(nil),
		(*EvaluationSuccess_StringValue)(nil),
		(*EvaluationSuccess_IntegerValue)(nil),
		(*EvaluationSuccess_DoubleValue)(nil),
		(*EvaluationSuccess_ObjectValue)(nil),
	}
	file_docs_schema_ofrep_v1_schema_proto_msgTypes[14].OneofWrappers = []interface{}{
		(*Metadata_BooleanValue)(nil),
		(*Metadata_StringValue)(nil),
		(*Metadata_NumberValue)(nil),
	}
	file_docs_schema_ofrep_v1_schema_proto_msgTypes[15].OneofWrappers = []interface{}{
		(*EvaluationResult_Success)(nil),
		(*EvaluationResult_Failure)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_docs_schema_ofrep_v1_schema_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docs_schema_ofrep_v1_schema_proto_goTypes,
		DependencyIndexes: file_docs_schema_ofrep_v1_schema_proto_depIdxs,
		MessageInfos:      file_docs_schema_ofrep_v1_schema_proto_msgTypes,
	}.Build()
	File_docs_schema_ofrep_v1_schema_proto = out.File
	file_docs_schema_ofrep_v1_schema_proto_rawDesc = nil
	file_docs_schema_ofrep_v1_schema_proto_goTypes = nil
	file_docs_schema_ofrep_v1_schema_proto_depIdxs = nil
}
