// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: docs/schema/ofrep/v1/schema.proto

package ofrep

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	OFREPService_GetConfiguration_FullMethodName  = "/ofrep.v1.OFREPService/GetConfiguration"
	OFREPService_EvaluateFlag_FullMethodName      = "/ofrep.v1.OFREPService/EvaluateFlag"
	OFREPService_EvaluateFlagsBulk_FullMethodName = "/ofrep.v1.OFREPService/EvaluateFlagsBulk"
)

// OFREPServiceClient is the client API for OFREPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OFREPServiceClient interface {
	GetConfiguration(ctx context.Context, in *GetConfigurationRequest, opts ...grpc.CallOption) (*GetConfigurationResponse, error)
	EvaluateFlag(ctx context.Context, in *EvaluateFlagRequest, opts ...grpc.CallOption) (*EvaluateFlagResponse, error)
	EvaluateFlagsBulk(ctx context.Context, in *EvaluateFlagsBulkRequest, opts ...grpc.CallOption) (*EvaluateFlagsBulkResponse, error)
}

type oFREPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOFREPServiceClient(cc grpc.ClientConnInterface) OFREPServiceClient {
	return &oFREPServiceClient{cc}
}

func (c *oFREPServiceClient) GetConfiguration(ctx context.Context, in *GetConfigurationRequest, opts ...grpc.CallOption) (*GetConfigurationResponse, error) {
	out := new(GetConfigurationResponse)
	err := c.cc.Invoke(ctx, OFREPService_GetConfiguration_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oFREPServiceClient) EvaluateFlag(ctx context.Context, in *EvaluateFlagRequest, opts ...grpc.CallOption) (*EvaluateFlagResponse, error) {
	out := new(EvaluateFlagResponse)
	err := c.cc.Invoke(ctx, OFREPService_EvaluateFlag_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oFREPServiceClient) EvaluateFlagsBulk(ctx context.Context, in *EvaluateFlagsBulkRequest, opts ...grpc.CallOption) (*EvaluateFlagsBulkResponse, error) {
	out := new(EvaluateFlagsBulkResponse)
	err := c.cc.Invoke(ctx, OFREPService_EvaluateFlagsBulk_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OFREPServiceServer is the server API for OFREPService service.
// All implementations should embed UnimplementedOFREPServiceServer
// for forward compatibility
type OFREPServiceServer interface {
	GetConfiguration(context.Context, *GetConfigurationRequest) (*GetConfigurationResponse, error)
	EvaluateFlag(context.Context, *EvaluateFlagRequest) (*EvaluateFlagResponse, error)
	EvaluateFlagsBulk(context.Context, *EvaluateFlagsBulkRequest) (*EvaluateFlagsBulkResponse, error)
}

// UnimplementedOFREPServiceServer should be embedded to have forward compatible implementations.
type UnimplementedOFREPServiceServer struct {
}

func (UnimplementedOFREPServiceServer) GetConfiguration(context.Context, *GetConfigurationRequest) (*GetConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfiguration not implemented")
}
func (UnimplementedOFREPServiceServer) EvaluateFlag(context.Context, *EvaluateFlagRequest) (*EvaluateFlagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluateFlag not implemented")
}
func (UnimplementedOFREPServiceServer) EvaluateFlagsBulk(context.Context, *EvaluateFlagsBulkRequest) (*EvaluateFlagsBulkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluateFlagsBulk not implemented")
}

// UnsafeOFREPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OFREPServiceServer will
// result in compilation errors.
type UnsafeOFREPServiceServer interface {
	mustEmbedUnimplementedOFREPServiceServer()
}

func RegisterOFREPServiceServer(s grpc.ServiceRegistrar, srv OFREPServiceServer) {
	s.RegisterService(&OFREPService_ServiceDesc, srv)
}

func _OFREPService_GetConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OFREPServiceServer).GetConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OFREPService_GetConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OFREPServiceServer).GetConfiguration(ctx, req.(*GetConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OFREPService_EvaluateFlag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateFlagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OFREPServiceServer).EvaluateFlag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OFREPService_EvaluateFlag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OFREPServiceServer).EvaluateFlag(ctx, req.(*EvaluateFlagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OFREPService_EvaluateFlagsBulk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateFlagsBulkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OFREPServiceServer).EvaluateFlagsBulk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OFREPService_EvaluateFlagsBulk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OFREPServiceServer).EvaluateFlagsBulk(ctx, req.(*EvaluateFlagsBulkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OFREPService_ServiceDesc is the grpc.ServiceDesc for OFREPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OFREPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ofrep.v1.OFREPService",
	HandlerType: (*OFREPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfiguration",
			Handler:    _OFREPService_GetConfiguration_Handler,
		},
		{
			MethodName: "EvaluateFlag",
			Handler:    _OFREPService_EvaluateFlag_Handler,
		},
		{
			MethodName: "EvaluateFlagsBulk",
			Handler:    _OFREPService_EvaluateFlagsBulk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "docs/schema/ofrep/v1/schema.proto",
}
