appEnv: local
retrievers:
  - type: file
    file:
      path: feature-flag/file.yaml
grpc: &grpc
  port: 40003
  endpoint: localhost
gateway:
  grpc: *grpc
  port: 8889
logging:
  level: debug
  handler:
    - json
    - datadog
tracking:
  enabled: false
  agentAddr: otel-collector:4317
  environment: local
raft:
  id: local-3
  join: localhost:40001
